{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE OverloadedStrings #-}
 
module CheckVerb where 
    
import Data.Text 

checkVerb :: Text -> Text 
checkVerb verb = 
    if | verb == "be" -> "Got it!    PastSimple:    was/were     PastParticiple:    benn"  
       | verb == "become" -> "Got it!    PastSimple:    became     PastParticiple:    become"  
       | verb == "begin" -> "Got it!    PastSimple:    began     PastParticiple:    begun"  
       | verb == "beat" -> "Got it!    PastSimple:beat PastParticiple:beaten  "
       | verb == "blow" -> "Got it! PastSimple: blew  PastParticiple: blown "
       | verb == "break" -> "Got it! PastSimple: broke  PastParticiple: broken "
       | verb == "bring" -> "Got it! PastSimple:brought PastParticiple: brought "
       | verb == "build" -> "Got it! PastSimple: built PastParticiple: built "
       | verb == "buy" -> "Got it! PastSimple: bought PastParticiple: bought "
       | verb == "catch" -> "Got it! PastSimple: caught  PastParticiple: caught "
       | verb == "choose" -> "Got it! PastSimple:chose PastParticiple: chosen"
       | verb == "come" -> "Got it! PastSimple: came  PastParticiple: come" 
       | verb == "cost" -> "Got it! PastSimple: cost  PastParticiple: cost "
       | verb == "cut" -> "Got it! PastSimple: cut  PastParticiple: cut "
       | verb == "dig" -> "Got it! PastSimple: dug  PastParticiple: dug "
       | verb == "do" -> "Got it! PastSimple: did  PastParticiple: done "
       | verb == "draw" -> "Got it! PastSimple: drew PastParticiple: drawn "
       | verb == "drink" -> "Got it! PastSimple: drank  PastParticiple: drunk "
       | verb == "drive" -> "Got it! PastSimple: drove  PastParticiple: driven "
       | verb == "eat"  -> "Got it! PastSimple: ate   PastParticiple: eaten "
       | verb == "fall" -> "Got it! PastSimple: fell  PastParticiple: fallen "
       | verb == "feed" -> "Got it! PastSimple: fed  PastParticiple: fed "
       | verb == "feel" -> "Got it! PastSimple: felt  PastParticiple: felt "
       | verb == "fight" -> "Got it!  PastSimple: fought  PastParticiple: fought"
       | verb == "find" -> "Get it!  PastSimple: found  PastParticiple: found "
       | verb == "fly" -> "Get it!  PastSimple: flew  PastParticiple: flown "
       | verb == "forget" -> "Got it! PastSimple: forgot  PastParticiple: forgotten"
       | verb == "forgive" -> "Got it! PastSimple: forgave  PastParticiple: forgiven"
       | verb == "freeze" -> "Got it! PastSimple: froze  PastParticiple:  frozen  "
       | verb == "get" -> "Got it!  PastSimple: got  PastParticiple:  got  "
       | verb == "give" -> "Got it!  PastSimple: gave   PastParticiple: given "
       | verb == "go" -> "Got it! PastSimple: went  PastParticiple: gone  "
       | verb == "grow" -> "Got it! PastSimple: grew  PastParticiple:  grown" 
       | verb == "have" -> "Got it!  PastSimple: had  PastParticiple: had " 
       | verb == "hold" -> "Got it!  PastSimple: held  PastParticiple:  held "
       | verb == "hurt" -> "Got it!  PastSimple:  hurt  PastParticiple: hurt "
       | verb == "keept" -> "Got it!  PastSimple: kept  PastParticiple:  kept "
       | verb == "leave" -> "Got it!  PastSimple: left  PastParticiple: left "
       | verb == "let" -> "Got it!  PastSimple: let  PastParticiple:  let "
       | verb == "lie" -> "Got it!  PastSimple: lay  PastParticiple: lain  "
       | verb == "lost" -> "Got it!  PastSimple: lost   PastParticiple: lost "
       | verb == "make" -> "Got it!  PastSimple:  made  PastParticiple:  made "
       | verb == "mean" -> "Got it!  PastSimple:  meant  PastParticiple: meant "
       | verb == "meet" -> "Got it!  PastSimple: met  PastParticiple:  met "
       | verb == "pay" -> "Got it ! PastSimple:  paid  PastParticiple:  paid "
       | verb == "put" -> "Got it!  PastSimple: put  PastSimple:  put  "
       | verb == "read" -> "Got it! PastSimple: read  PastParticiple:  read "
       | verb == "ride" -> "Got it! PastSimple: rode  PastParticiple:  ridden "
       | verb == "ring" -> "Got it!  PastSimple: rang  PastParticiple:  rung "
       | verb == "rise" -> "Got it! PastSimple: rose  PastParticiple: risen "
       | verb == "run" -> "Got it! PastSimple: ran  PastParticiple: run "
       | verb == "say" -> "Got it!  PastSimple: said  PastParticiple:  said "
       | verb == "see" -> "Got it! PastSimple: saw  PastParticiple: seen "
       | verb == "sell" -> "Got it! PastSimple: sold  PastParticiple: sold "
       | verb == "send" -> "Got it! PastSimple: sent  PastParticiple: sent "
       | verb == "set" -> "Got it! PastSimple: set  PastParticiple: set "
       | verb == "sleep" -> "Got it! PastSimple: slept  PastParticiple: slept "
       | verb == "swim" -> "Got it! PastSimple: swam  PastParticiple: swum "
       | verb == "take" -> "Got it!  PastSimple: took  PastParticiple: taken "
       | otherwise -> "Please make sure that you entered the correct word without 'to' if everything is okay with it, then it may simply not be in the program"
